Feature/add datasources contribs diff stix
mitre-attack/attack-scripts pull request #72
Opened 2021-10-07 13:43 UTC by IanDavila

PR to update `diff-stix.py` script to include data sources and contributors section when selecting markdown option.

New contributors are calculated as defined in #71 and script was tested for `If a contributor is removed from an object and (not re-added on a different object)`.

`data["new_contributors"]` will contain a dictionary of keys (names of contributors) and values (number of new contributions for the release) after the `load_data()` functions runs.

PR also adds new argument `--use-mitre-cti` that downloads the MITRE CTI bundles specified by the domains that may be used for the `old` comparison.

Closes #70, #71.

2021-10-15 15:47 UTC, isaisabel requested changes
- Needs CHANGELOG update
- Seems to crash when generating the markdown key
- Might want to move some of the data around internally to make it more organized.

2021-10-15 15:47 UTC, isaisabel commented on scripts/diff_stix.py
> +                                self.data["new_contributors"][new_contributor] += 1
The comment for `self.data = {}` includes a comment documenting what it holds -- this field should be reflected there for future reference.

2021-10-15 15:47 UTC, isaisabel commented on scripts/diff_stix.py
> +                                self.data["new_contributors"][new_contributor] += 1
That is currently on line 124.

2021-10-15 15:47 UTC, isaisabel commented on scripts/diff_stix.py
> +            if obj_type == "new_contributors": continue # Skip new contributors
I'm not sure that contributor changes should be kept in the `data` field if it's not being ingested this way. It probably makes the most sense to be it's own field (`self.contributors`) so that `data` can store purely STIX object changes.

2021-10-15 15:47 UTC, isaisabel commented on scripts/diff_stix.py
> +            if obj_type == "new_contributors": continue # Skip new contributors
Also, `obj_type` doesn't exist here and causes a crash:
```
$ python3 diff_stix.py -v --show-key --contributors --minor-changes -markdown
generating markdown string... Traceback (most recent call last):
  File "diff_stix.py", line 824, in <module>
    md_string = diffStix.get_markdown_string()
  File "diff_stix.py", line 585, in get_markdown_string
    key_content = self.get_md_key()
  File "diff_stix.py", line 406, in get_md_key
    if obj_type == "new_contributors": continue # Skip new contributors
NameError: name 'obj_type' is not defined
```

2021-10-18 13:50 UTC, isaisabel approved these changes
While I do have comments below, I am approving this PR since it does work and match the standards of this repository.

2021-10-18 13:50 UTC, isaisabel commented on scripts/diff_stix.py
> +        self.release_contributors = {} # will hold information of contributors of the new release {... {"contributor_credit/name_as_key": counter]} ...}
Not worth changing now, but worth pointing out that this could very easily have been implemented as a [Counter](https://docs.python.org/3/library/collections.html#collections.Counter), which includes some nifty quality-of-life features for counting occurrences.

2021-10-18 13:50 UTC, isaisabel commented on scripts/diff_stix.py
> +                    stix_json = requests.get(f"https://raw.githubusercontent.com/mitre/cti/master/{domain}/{domain}.json", verify=False)
`verify` should not be set to false here.

2021-10-18 15:37 UTC, isaisabel approved these changes
HTML conversion is fantastic, great addition!

2023-12-11 17:06 UTC, jondricek commented
Admin note: closing all remaining issues and pull requests prior to archiving the repository

2023-12-11 17:06 UTC, closed without merging